const list ={
    "3d_affair_main_icon_10.png": [],
    "3d_affair_main_icon_left_01.png": [],
    "3d_affair_main_icon_left_02.png": [
        '3d_baowu_detail.csd',
        '3d_baowu_tips.csd',
        '3d_recruit_card_summon_chouka.csd',
        '3d_recruit_card_summon_main_ui.csd',
        '3d_sys_com_share.csd',
    ],
    "3d_affair_main_icon_left_05.png": [
        '3d_army_conscription_main.csd',
        '3d_hero_card_operate_main.csd',
        '3d_recruit_card_summon_main_ui.csd',
        '3d_skill_main.csd'
    ],
    "3d_affair_shangdui_icon.png": [
        '3d_affair_bottom.csd',
        '3d_baowu_list.csd'
    ],
    "3d_army_btn_lock.png": [
        '3d_army_conscripting_number.csd'
    ],
    "3d_army_btn_lock_un.png": [],
    "3d_btn_add.png": [
        '3d_activity_baowu.csd',
        '3d_army_main.csd',
        '3d_armymove_qixie_select.csd',
        '3d_baowu_detail.csd',
        '3d_baowu_transaction_main.csd',
        '3d_hero_attribute_panel_item.csd',
        '3d_hero_card_detail_container.csd',
        '3d_hero_card_operate_main.csd',
        '3d_hero_details_right_cultivate.csd',
        '3d_hero_list.csd',
        '3d_main.csd',
        '3d_pictureshop_gift_info.csd',
        '3d_pictureshop_gift.csd',
        '3d_pictureshop_main.csd',
        '3d_recruit_card_summon_main_ui.csd',
        '3d_skill_bottom_exp.csd',
        '3d_skill_list.csd',
        '3d_sys_bottom_hufu.csd',
        '3d_tcxb_main.csd',
    ],
    "3d_btn_lose.png": [
        '3d_armymove_qixie_select.csd',
        '3d_hero_attribute_panel_item.csd',
    ],
    "3d_btn_lose_z.png": [
        '3d_hero_attribute_panel_item.csd'
    ],
    "3d_btn_select.png": [
        '3d_pay_main.csd'
    ],
    "3d_btn_yaoqingsai_shaizi.png": [
        '3d_invitational2021_team_create.csd'
    ],
    "3d_chat_btn_01.png": [
        '3d_chat_main.csd'
    ],
    "3d_chat_btn_02.png": [
        '3d_chat_main.csd',
        '3d_map_item_title.csd'
    ],
    "3d_chat_btn_back_a.png": [
        '3d_invitational2021_info_input.csd',
        '3d_mail_send.csd'
    ],
    "3d_chat_btn_emoticon.png": [
        '3d_chat_main.csd',
        '3d_friends_main.csd',
        '3d_invitational2021_info_input.csd',
        '3d_mail_send.csd',
        '3d_sys_com_chatbase.csd',
    ],
    "3d_chat_btn_emoticon_s.png": [
        '3d_chat_main.csd',
        '3d_friends_main.csd',
        '3d_mail_send.csd',
    ],
    "3d_chat_btn_mic.png": [
        '3d_chat_main.csd',
        '3d_friends_main.csd'
    ],
    "3d_chat_btn_txt.png": [
        '3d_invitational2021_info_input.csd',
        '3d_mail_send.csd',
    ],
    "3d_cityname_btn_share.png": [],
    "3d_cityname_going_icon_bg_02_s.png": [],
    "3d_com_btn_refresh.png": [
        '3d_baowu_transaction_sort.csd',
        '3d_sys_com_sizer.csd',
        '3d_sys_sizer.csd',
    ],
    "3d_com_btn_refresh_s.png": [
        '3d_sys_com_sizer.csd',
        '3d_sys_sizer.csd'
    ],
    "3d_com_icon_arrow_02.png": [
        '3d_2021_fubi.csd',
        '3d_2021_gonghuiliuzai_main.csd',
        '3d_2021_jiyishujuan_sgjy.csd',
        '3d_2021_sanguoyi_ranking.csd',
        '3d_2021guoqing_main.csd',
        '3d_2021guoqing_reward_explain.csd',
        '3d_2021guoqing_shangxi.csd',
        '3d_2021huigui_huiguihaoli.csd',
        '3d_2021huigui_zhaohuijiangli.csd',
        '3d_2021minghao_homepage.csd',
        '3d_2021minghao_main.csd',
        '3d_2021zhongqiu_qifu_main.csd',
        '3d_2021zhongqiu_qifu_reward.csd',
        '3d_2021zhongqiu_youdeng_main.csd',
        '3d_activity_com_gongcheng.csd',
        '3d_activity_com_liangchenzhizhu.csd',
        '3d_activity_com_reward_item.csd',
        '3d_activity_com_shili.csd',
        '3d_activity_com_zhaoxian.csd',
        '3d_activity_forging.csd',
        '3d_activity_fuli.csd',
        '3d_activity_home.csd',
        '3d_activity_jijin.csd',
        '3d_activity_supermember.csd',
        '3d_affair_head.csd',
        '3d_affair_instruction.csd',
        '3d_affair_policy_appoint.csd',
        '3d_affair_policy_pop_value.csd',
        '3d_affair_policy_result_tips.csd',
        '3d_affair_pop_market.csd',
        '3d_affair_pop_qiancheng.csd',
        '3d_affair_pop_technology.csd',
        '3d_alliance_calendar_item_1.csd',
        '3d_alliance_calendar_item_5.csd',
        '3d_alliance_forces_hemeng_apply.csd',
        '3d_alliance_forces.csd',
        '3d_alliance_invitation.csd',
        '3d_alliance_join.csd',
        '3d_alliance_liguo_choose.csd',
        '3d_alliance_liguo_rule.csd',
        '3d_alliance_log.csd',
        '3d_alliance_main.csd',
        '3d_alliance_member_apply.csd',
        '3d_alliance_member_group_jurisdiction.csd',
        '3d_alliance_member_group_move.csd',
        '3d_alliance_member_group_renming.csd',
        '3d_alliance_member_group.csd',
        '3d_alliance_member_invitation_player.csd',
        '3d_alliance_member.csd',
        '3d_alliance_policy_main.csd',
        '3d_alliance_policy_open.csd',
        '3d_alliance_policy.csd',
        '3d_alliance_power_invitation.csd',
        '3d_alliance_power_process.csd',
        '3d_alliance_power.csd',
        '3d_alliance_qiandu_choose.csd',
        '3d_alliance_tag_jijie_item.csd',
        '3d_army_map_transfer.csd',
        '3d_armymove_main.csd',
        '3d_baowu_baowujieshao.csd',
        '3d_baowu_dazao.csd',
        '3d_baowu_detail.csd',
        '3d_baowu_list.csd',
        '3d_baowu_mix_content.csd',
        '3d_baowu_tips.csd',
        '3d_baowu_trade_comfirm.csd',
        '3d_baowu_transaction_main.csd',
        '3d_baowu_transaction_record.csd',
        '3d_baowu_transaction_sort.csd',
        '3d_baowu_transaction_trading.csd',
        '3d_bhcc_build_ui.csd',
        '3d_bhcc_create_ui.csd',
        '3d_build_main_ui.csd',
        '3d_chat_emoji.csd',
        '3d_chat_main.csd',
        '3d_chat_union_group_list_ui.csd',
        '3d_chat_union_group_set_ui.csd',
        '3d_chenqing_ambitious_plans_main.csd',
        '3d_chenqing_right_immediately.csd',
        '3d_chenqing_solarterm_progress.csd',
        '3d_chenqing_strategic_target_details.csd',
        '3d_chenqing_strategic_target_main.csd',
        '3d_chenqing.csd',
        '3d_createcity_state.csd',
        '3d_exercise_home.csd',
        '3d_exercise_records.csd',
        '3d_forces_city.csd',
        '3d_forces_construction.csd',
        '3d_forces_detail.csd',
        '3d_forces_economics.csd',
        '3d_friends_main.csd',
        '3d_gamesprite_content_2.csd',
        '3d_gamesprite_question.csd',
        '3d_hero_awakening.csd',
        '3d_hero_card_detail_container.csd',
        '3d_hero_card_operate_main.csd',
        '3d_hero_details_right_desc.csd',
        '3d_hero_details_right_facade.csd',
        '3d_hero_details_right_hero_type.csd',
        '3d_hero_list.csd',
        '3d_heropicture_ui.csd',
        '3d_herosolaier_comp.csd',
        '3d_herosolaier_detail_right.csd',
        '3d_herosolaier_detail.csd',
        '3d_herosolaier_feature_list.csd',
        '3d_honor_card_detail_view.csd',
        '3d_huigui_dialog_beizhan.csd',
        '3d_huiliu_list_new.csd',
        '3d_huiliu_list.csd',
        '3d_huiliu_teamlist.csd',
        '3d_invitational_map_pop_stws.csd',
        '3d_invitational_map_popup_big_battle.csd',
        '3d_invitational_map_popup_lasting_war.csd',
        '3d_invitational_map_popup_shiguan.csd',
        '3d_invitational2021_entrance.csd',
        '3d_invitational2021_guide .csd',
        '3d_invitational2021_main_information.csd',
        '3d_invitational2021_main.csd',
        '3d_invitational2021_team_invite.csd',
        '3d_jiaozhen_main.csd',
        '3d_jiaozhen_popup.csd',
        '3d_land_tips_build_drag_view.csd',
        '3d_land_tips_march.csd',
        '3d_legion_detail.csd',
        '3d_legion_gathered_army_list.csd',
        '3d_login_agreement.csd',
        '3d_login_notice.csd',
        '3d_login_select_role_ui_beiyong.csd',
        '3d_login_select_role_ui.csd',
        '3d_login_server_list.csd',
        '3d_login_theme.csd',
        '3d_mail_linkman_list.csd',
        '3d_mail_main.csd',
        '3d_mail_send.csd',
        '3d_main_icon_horse.csd',
        '3d_main_location.csd',
        '3d_main_state.csd',
        '3d_main.csd',
        '3d_map_.csd.csd',
        '3d_map_detail.csd',
        '3d_map_main.csd',
        '3d_map_main.csd.csd',
        '3d_mastbook_friends_manager.csd',
        '3d_mastbook_friends_process_application.csd',
        '3d_mastbook_friends_search_friends.csd',
        '3d_mastbook_saiceng_grlc.csd',
        '3d_mastbook_saicheng.csd',
        '3d_mastbook_zhengcheng.csd',
        '3d_masterbook_record.csd',
        '3d_mission_main.csd',
        '3d_mod_linbingliezhen_emoji_ui.csd',
        '3d_mod_linbingliezhen_event.csd',
        '3d_mod_linbingliezhen_info.csd',
        '3d_mod_linbingliezhen_main.csd',
        '3d_mod_linbingliezhen_troops.csd',
        '3d_mod_result.csd',
        '3d_mod_roomlist.csd',
        '3d_pay_main.csd',
        '3d_pay_process.csd',
        '3d_picturebook_hero_introduce.csd',
        '3d_picturebook_list.csd',
        '3d_picturebook_scenic_reward.csd',
        '3d_pictureshop_gift.csd',
        '3d_pictureshop_item_list.csd',
        '3d_pictureshop_main.csd',
        '3d_qxzl_technology.csd',
        '3d_ranking_main_ui.csd',
        '3d_ranking_tips.csd',
        '3d_recruit_card_summon_main_ui.csd',
        '3d_recruit_exchange_detail_ui.csd',
        '3d_recruit_operate_exchange.csd',
        '3d_recruit_quick_summon_result_ui.csd',
        '3d_report_detail_board.csd',
        '3d_report_detail.csd',
        '3d_report_list.csd',
        '3d_report_main.csd',
        '3d_seal_nobility_show.csd',
        '3d_seal_nobility_show.csd',
        '3d_seal_strategy_alliance.csd',
        '3d_seal_strategy_list.csd',
        '3d_set_gonggao.csd',
        '3d_set_realname.csd',
        '3d_shujia_note.csd',
        '3d_skill_list.csd',
        '3d_skill_main.csd',
        '3d_skill_pop_details_item.csd',
        '3d_sys_com_chatbase.csd',
        '3d_sys_com_sizer.csd',
        '3d_sys_pop_1.csd',
        '3d_sys_pop_3.csd',
        '3d_sys_pop_input_com.csd',
        '3d_sys_scroll_view.csd',
        '3d_sys_tips_btn_01.csd',
        '3d_tab_up_1.csd',
        '3d_tab_up_2.csd',
        '3d_tab_up_3.csd',
        '3d_tcxb_course.csd',
        '3d_transfer_enter.csd',
        '3d_transfer_main.csd',
        '3d_transfer_pop_confirm.csd',
        '3d_transfer_servers.csd',
        '3d_tslh_fulu.csd',
        '3d_weather_main.csd',
        '3d_world_main.csd',
        '3d_world_season_wait_fu_item.csd',
        '3d_world_state_item.csd',
        '3d_zfjx_copy_skill.csd',
        '3d_zfjx_invitation.csd',
        '3d_zfjx_ranking.csd',
        '3d_zfjx_select_show.csd',
        '3d_zfjx_select.csd',
        '3d_zfjx_skill_item.csd',
        '3d_zfjx_tech.csd',
    ],
    "3d_com_icon_arrow_05.png": [
        '3d_2021huigui_shachangjushou.csd',
        '3d_army_conscription_main.csd',
        '3d_army_main.csd',
        '3d_chenqing_solarterm_conversation.csd',
        '3d_legion_detail.csd',
        '3d_legion_expedition_army_list.csd',
    ],
    "3d_com_icon_arrow_11.png": [
        '3d_gamesprite_main.csd'
    ],
    "3d_com_icon_bofang.png": [
        '3d_chenqing_right_card.csd'
    ],
    "3d_com_icon_close.png": [
        '3d_land_tips_info.csd',
        '3d_main_location.csd',
        '3d_map_item_self_qx.csd',
        '3d_map_item_self.csd',
        '3d_map_item_union_mark.csd',
        '3d_transfer_join.csd'
    ],
    "3d_com_icon_close_red.png": [
        '3d_affair_head.csd',
        '3d_alliance_forces.csd',
        '3d_alliance_join.csd',
        '3d_alliance_member_group_create.csd',
        '3d_alliance_member_invitation_player.csd',
        '3d_alliance_member.csd',
        '3d_cclive_main.csd',
        '3d_chat_union_group_set_ui.csd',
        '3d_create_city_name_ui.csd',
        '3d_invitational_map_pinglun.csd',
        '3d_invitational2021_main.csd',
        '3d_invitational2021_team_details.csd',
        '3d_invitational2021_team_invite.csd',
        '3d_mail_linkman_list.csd',
        '3d_main_location_pop.csd',
        '3d_mastbook_friends_search_friends.csd',
        '3d_mod_check.csd',
        '3d_mod_createroom.csd',
        '3d_mod_roomlist.csd',
        '3d_report_list.csd',
        '3d_skill_list.csd',
        '3d_transfer_join.csd',
        '3d_transfer_team_list.csd',
    ],
    "3d_com_icon_copy.png": [
        '3d_forces_detail.csd',
        '3d_invitational2021_list_item_details.csd',
        '3d_set_main.csd',
    ],
    "3d_com_icon_edit.png": [
        '3d_alliance_main.csd',
        '3d_forces_detail.csd',
        '3d_invitational2021_info_input.csd',
        '3d_mail_send.csd',
        '3d_masterbook_home.csd',
        '3d_pictureshop_gift_info.csd',
    ],
    "3d_com_icon_like_01.png": [
        '3d_sys_com_danmu.csd'
    ],
    "3d_com_icon_like_02.png": [
        '3d_sys_com_danmu.csd'
    ],
    "3d_com_icon_like_03.png": [
        '3d_sys_com_danmu.csd'
    ],
    "3d_com_icon_share.png": [
        '3d_chat_share_army.csd',
        '3d_chat_share_baowu.csd',
        '3d_chat_share_gift.csd',
        '3d_chat_share_herocard.csd',
        '3d_chat_share_invitation.csd',
        '3d_chat_share_mod.csd',
        '3d_chat_share_red_packet.csd',
        '3d_chat_share_report.csd',
        '3d_chat_share_shuajia.csd',
        '3d_chat_share_soldier.csd',
        '3d_mail_cell_mod.csd',
    ],
    "3d_com_icon_share_01.png": [
        '3d_report_result.csd'
    ],
    "3d_com_icon_star.png": [
        '3d_baowu_detail.csd',
        '3d_baowu_transaction_item.csd',
        '3d_invitational2021_list_item_details.csd',
        '3d_invitational2021_team_details.csd',
        '3d_mail_main.csd',
    ],
    "3d_com_special_icon_01.png": [
        '3d_6th_main.csd',
        '3d_2021_sanguoyi_main.csd',
        '3d_baowu_detail.csd',
        '3d_huiliu_teamlist.csd',
        '3d_invitational2021_team_beinvited.csd',
        '3d_transfer_team_apply.csd',
        '3d_transfer_team_beinvited.csd',
        '3d_transfer_team_biaoji.csd',
        '3d_transfer_team_list.csd',
    ],
    "3d_com_special_icon_eye.png": [
        '3d_armymove_camp.csd'
    ],
    "3d_friends_btn_profile.png": [],
    "3d_friends_profile.png": [
        '3d_friends_main.csd'
    ],
    "3d_hero_btn_lock.png": [
        '3d_baowu_detail.csd',
        '3d_hero_card_detail_container.csd',
        '3d_mod_room.csd',
        '3d_mod_roomlist.csd',
    ],
    "3d_hero_btn_lock_s.png": [
        '3d_baowu_detail.csd',
    ],
    "3d_hero_btn_wu.png": [],
    "3d_hero_icon_01.png": [
        '3d_2021_gonghuiliuzai_bless.csd',
        '3d_2021_jiyishujuan_enter.csd',
        '3d_2021_jiyishujuan_history.csd',
        '3d_2021_jiyishujuan_yeqian.csd',
        '3d_2021guoqing_main.csd',
        '3d_2021guoqing_shanhetu.csd',
        '3d_2021zhongqiu_qifu_login.csd',
        '3d_army_array.csd',
        '3d_chenqing_solarterm_login.csd',
        '3d_hero_card_detail_container.csd',
        '3d_heropicture_picture.csd',
        '3d_heropicture_ui.csd',
        '3d_invitational_map_event_zhuwei.csd',
        '3d_invitational2021_team_details.csd',
        '3d_mastbook_saicheng.csd',
        '3d_mod_room.csd',
        '3d_picturebook_scenic_introduce.csd',
        '3d_pictureshop_gift_info.csd',
        '3d_report_detail.csd',
        '3d_seal_imperial_edict.csd',
        '3d_shujia_event.csd',
        '3d_shujia_jingdian.csd',
        '3d_shujia_note.csd',
    ],
    "3d_hero_icon_02.png": [
        '3d_baowu_dazao.csd',
        '3d_baowu_detail.csd',
        '3d_hero_card_detail_container.csd',
    ],
    "3d_hero_icon_03.png": [
        '3d_hero_list.csd',
    ],
    "3d_hero_icon_04.png": [
        '3d_picturebook_list.csd'
    ],
    "3d_hero_icon_05.png": [
        '3d_picturebook_list.csd'
    ],
    "3d_hero_icon_06.png": [
        '3d_hero_card_detail_container.csd'
    ],
    "3d_hero_icon_07.png": [
        '3d_baowu_mix_content.csd',
        '3d_land_tips_event_details_scenic.csd',
        '3d_skill_list.csd',
    ],
    "3d_hero_icon_08.png": [
        '3d_hero_card_detail_container.csd'
    ],
    "3d_hero_icon_09.png": [
        '3d_invitational2021_main.csd',
        '3d_report_detail.csd'
    ],
    "3d_hero_icon_09_s.png": [
        '3d_invitational2021_main.csd',
        '3d_report_detail.csd'
    ],
    "3d_hero_icon_10.png": [
        '3d_picturebook_scenic_visit.csd',
        '3d_skill_list.csd'
    ],
    "3d_hero_icon_11.png": [
        '3d_world_main.csd'
    ],
    "3d_hero_icon_12.png": [
        '3d_kabao.csd'
    ],
    "3d_hero_icon_13.png": [
        '3d_mastbook_saiceng_grlc.csd',
        '3d_mastbook_zhengcheng.csd'
    ],
    "3d_hero_icon_14.png": [
        '3d_hero_details_right_hero_type.csd',
        '3d_herosolaier_comp.csd'
    ],
    "3d_hero_icon_15.png": [
        '3d_hero_card_detail_container.csd'
    ],
    "3d_hero_icon_16.png": [],
    "3d_hero_icon_17.png": [
        '3d_army_conscripting_number.csd',
        '3d_army_conscription_main.csd',
        '3d_armymove_camp.csd',
        '3d_forces_economics.csd',
        '3d_sys_pop_m.csd',
    ],
    "3d_hero_icon_army.png": [],
    "3d_hero_icon_bachu.png": [],
    "3d_hero_icon_baowu.png": [
        '3d_baowu_transaction_main.csd'
    ],
    "3d_hero_icon_chaijiezhanfa.png": [],
    "3d_hero_icon_dashen.png": [
        '3d_invitational2021_main.csd',
        '3d_invitational2021_team_details.csd',
    ],
    "3d_hero_icon_dengyong.png": [],
    "3d_hero_icon_message.png": [
        '3d_2021_jiyishujuan_history.csd'
    ],
    "3d_hero_icon_years.png": [
        '3d_hero_details_right_desc.csd',
        '3d_picturebook_hero_introduce.csd'
    ],
    "3d_jilue_btn_abandon.png": [
        '3d_affair_hero_appoint_entrance.csd',
        '3d_land_tips_build_drag_view.csd'
    ],
    "3d_jilue_btn_confirm.png": [
        '3d_land_tips_build_drag_view.csd'
    ],
    "3d_jiyishujuan_icon_message.png": [],
    "3d_main_btn_05.png": [],
    "3d_masterbook_relation.png": [
        '3d_huiliu_list_new.csd',
        '3d_mastbook_friends_manager.csd'
    ],
    "3d_masterbook_relation_02.png": [],
    "3d_masterbook_relation_btn_friends.png": [
        '3d_2021huigui_huiliumingpu.csd'
    ],
    "3d_masterbook_saicheng_btn_kuaijin.png": [
        '3d_mastbook_saiceng_main.csd',
        '3d_report_main.csd'
    ],
    "3d_service_centre_icon_01.png": [],
    "3d_service_centre_icon_02.png": [],
    "3d_service_centre_icon_03.png": [],
    "3d_service_centre_icon_04.png": [],
    "3d_service_centre_icon_05.png": [],
    "3d_special_btn_01.png": [
        '3d_alliance_member_apply_node.csd',
        '3d_alliance_member_apply.csd',
        '3d_alliance_member_group_create_node.csd',
        '3d_alliance_member_group_create.csd',
        '3d_army_conscripting_number.csd',
        '3d_bhcc_build_ui.csd',
        '3d_bhcc_destroy.csd',
        '3d_build_city_ui.csd',
        '3d_cclive_card_normal.csd',
        '3d_cclive_card_unlive.csd',
        '3d_chat_union_group_set_ui.csd',
        '3d_createcity_create_taishoufu_ui.csd',
        '3d_forces_construction.csd',
        '3d_forces_economics.csd',
        '3d_invitational2021_team_beinvited.csd',
        '3d_login_main.csd',
        '3d_mastbook_friends_process_application.csd',
        '3d_skill_pop_details.csd',
        '3d_transfer_team_beinvited.csd',
        '3d_zfjx_skill.csd',
    ],
    "3d_special_btn_02.png": [
        '3d_login_saoma.csd'
    ],
    "3d_special_btn_03.png": [
        '3d_allaince_member_editgroup_node.csd',
        '3d_alliance_forces_node.csd',
        '3d_alliance_forces.csd',
        '3d_alliance_member_group_node.csd',
        '3d_alliance_member_group.csd',
        '3d_alliance_member_node.csd',
        '3d_alliance_member.csd',
        '3d_alliance_power.csd',
        '3d_invitational_map_event_zhuwei.csd',
        '3d_invitational2021_team_details.csd',
        '3d_login_saoma.csd',
        '3d_main_location.csd',
        '3d_map_item_union_mark.csd',
        '3d_transfer_team.csd',
    ],
    "3d_special_btn_04.png": [],
    "3d_special_btn_05.png": [
        '3d_alliance_member_group_create.csd',
        '3d_bhcc_destroy.csd',
        '3d_chat_union_group_set_ui.csd',
    ],
    "3d_special_btn_06.png": [
        '3d_alliance_member_apply_node.csd',
        '3d_alliance_member_apply.csd',
        '3d_alliance_member_apply.csd',
        '3d_mastbook_friends_process_application.csd',
        '3d_transfer_team_beinvited.csd'
    ],
    "3d_special_btn_07.png": [
        '3d_world_state_map.csd'
    ],
    "3d_special_btn_09.png": [
        '3d_bhcc_destroy.csd'
    ],
    "3d_special_btn_10.png": [],
    "3d_special_btn_liji.png": [
        '3d_build_option_left.csd',
        '3d_land_tips_3dcityname.csd',
    ],
    "3d_yaoqingsai_btn_zhuweibang.png": [
        '3d_invitational_map_event_zhuwei.csd'
    ],
    "3dui_cityname_going_icon_bg_02.png": [],
    "3dui_cityname_going_icon_bg_02_s.png": [],
    "3dui_com_icon_ask.png": [
        '3d_2021guoqing_login.csd',
        '3d_2021zhongqiu_qifu_main.csd',
        '3dui_city_npc_fenhui.csd',
    ],
    "c3d_com_btn_pull.png": [
        '3d_login_server_list.csd',
        '3d_mail_main.csd',
    ],
    "c3d_com_btn_pull_s.png": [
        '3d_army_map_transfer.csd'
    ],
    "c3d_com_icon_ask.png": [
        '3d_2021_fubi.csd',
        '3d_2021_gonghuiliuzai_main.csd',
        '3d_2021_jiyishujuan_enter.csd',
        '3d_2021minghao_homepage.csd',
        '3d_2021zhongqiu_qifu_main.csd',
        '3d_2021zhongqiu_youdeng_main.csd',
        '3d_activity_baowu.csd',
        '3d_activity_com_experience.csd',
        '3d_activity_forging.csd',
        '3d_affair_main.csd',
        '3d_affair_policy_appoint.csd',
        '3d_affair_policy_main.csd',
        '3d_affair_pop_government.csd',
        '3d_army_main.csd',
        '3d_armymove_camp.csd',
        '3d_armymove_main.csd',
        '3d_armymove_tips.csd',
        '3d_bhcc_operation_view.csd',
        '3d_born_select_region.csd',
        '3d_chenqing_right_card.csd',
        '3d_chenqing_right_immediately.csd',
        '3d_chenqing_right_main.csd',
        '3d_createcity_operate_view.csd',
        '3d_exercise_home.csd',
        '3d_exercise_select_level_item.csd',
        '3d_guild_function_army.csd',
        '3d_huiliu_page_zzht.csd',
        '3d_invitational_map_event_zhuwei.csd',
        '3d_invitational2021_entrance.csd',
        '3d_invitational2021_guide .csd',
        '3d_invitational2021_main.csd',
        '3d_invitational2021_team_details.csd',
        '3d_kabao_3dhuaxiang.csd',
        '3d_legion_move_ui.csd',
        '3d_login_server_list.csd',
        '3d_main_army.csd',
        '3d_mod_linbingliezhen_event.csd',
        '3d_mod_main.csd',
        '3d_mod_room.csd',
        '3d_newbie_baohu.csd',
        '3d_nightmode_main.csd',
        '3d_pictureshop_gift.csd',
        '3d_pictureshop_main.csd',
        '3d_qxtd_zhaoji.csd',
        '3d_recruit_card_summon_cell.csd',
        '3d_recruit_card_summon_combine_ui.csd',
        '3d_recruit_card_summon_main_ui.csd',
        '3d_seal_strategy_military_officer.csd',
        '3d_shujia_intro.csd',
        '3d_sys_pop_full_back_1.csd',
        '3d_sys_pop_full_back_2.csd',
        '3d_sys_pop_full.csd',
        '3d_sys_pop_l.csd',
        '3d_sys_pop_m.csd',
        '3d_tcxb_main.csd',
        '3d_tcxb_selection.csd',
        '3d_transfer_enter.csd',
        '3d_transfer_team_biaoji.csd',
    ],
    "c3d_icon_arrow_01.png": [
        '3d_login_main.csd'
    ],
    "c3d_icon_arrow_02.png": [
        '3d_2021_gonghuiliuzai_bless.csd',
        '3d_2021_jiyishujuan_history.csd',
        '3d_activity_com_liangchenzhizhu.csd',
        '3d_alliance_calendar.csd',
        '3d_baowu_detail.csd',
        '3d_build_main_ui.csd',
        '3d_guild_function_3.csd',
        '3d_guild_function_4.csd',
        '3d_invitational_map_power_mesg_intro.csd',
        '3d_mod_linbingliezhen_guide.csd',
        '3d_pay_pop_fail.csd',
        '3d_qxzl_guide_view.csd',
        '3d_recruit_card_summon_main_ui.csd',
        '3d_sys_com_back.csd',
    ],
    "c3d_login_btn_army.png": [],
    "l3d_login_function_btn_07.png": [
        '3d_login_main.csd'
    ],
    "c3d_btn_back_01.png": [],
    "c3d_btn_back_02.png": [
        '3d_6th_main.csd',
        '3d_2021_fubi.csd',
        '3d_2021_gonghuiliuzai_bless.csd',
        '3d_2021_gonghuiliuzai_content.csd',
        '3d_2021_gonghuiliuzai_main.csd',
        '3d_2021_jiyishujuan_enter.csd',
        '3d_2021_jiyishujuan_history.csd',
        '3d_2021_jiyishujuan_sgjy.csd',
        '3d_2021_jiyishujuan_yeqian.csd',
        '3d_2021_sanguoyi_main.csd',
        '3d_2021guoqing_choose_mission.csd',
        '3d_2021guoqing_login.csd',
        '3d_2021guoqing_main.csd',
        '3d_2021guoqing_shangxi.csd',
        '3d_2021guoqing_shanhetu.csd',
        '3d_2021guoqing_tutorial.csd',
        '3d_2021huigui_huiguihaoli.csd',
        '3d_2021huigui_shachangjushou_wuzhanyou.csd',
        '3d_2021huigui_shachangjushou.csd',
        '3d_2021zhongqiu_qifu_login.csd',
        '3d_2021zhongqiu_qifu_main.csd',
        '3d_2021zhongqiu_youdeng_main.csd',
        '3d_affair_policy_appoint.csd',
        '3d_armymove_camp.csd',
        '3d_armymove_main.csd',
        '3d_born_region_state_ui.csd',
        '3d_born_select_region.csd',
        '3d_chenqing_solarterm_login.csd',
        '3d_huiliu_page_zzht.csd',
        '3d_invitational2021_entrance.csd',
        '3d_invitational2021_guide .csd',
        '3d_invitational2021_main.csd',
        '3d_kabao_3dhuaxiang.csd',
        '3d_mod_linbingliezhen_main.csd',
        '3d_qxzl_guide_view.csd',
        '3d_seal_strategy_military_officer.csd',
        '3d_sys_pop_full_back_1.csd',
        '3d_sys_pop_full_back_2.csd',
    ],
    "c3d_btn_close_l.png": [
        '3d_2021_gonghuiliuzai_main.csd',
        '3d_2021_sanguoyi_lottery.csd',
        '3d_activity_baowu.csd',
        '3d_activity_com_chongzhi.csd',
        '3d_activity_com_denglu.csd',
        '3d_activity_com_experience.csd',
        '3d_activity_com_gongcheng.csd',
        '3d_activity_com_gongpinlibao_huode.csd',
        '3d_activity_com_gongpinlibao.csd',
        '3d_activity_com_shapan.csd',
        '3d_activity_com_shili.csd',
        '3d_activity_com_zhaoxian.csd',
        '3d_activity_forging.csd',
        '3d_activity_fuli.csd',
        '3d_activity_shichangshi.csd',
        '3d_affair_policy_appoint.csd',
        '3d_alliance_main.csd',
        '3d_baowu_detail.csd',
        '3d_baowu_tips.csd',
        '3d_cclive_live_room.csd',
        '3d_createcity_jilue_ui.csd',
        '3d_hero_card_detail_container.csd',
        '3d_invitational_map_pop_stws.csd',
        '3d_invitational_map_pop_sxpm.csd',
        '3d_invitational_map_pop_wfzz.csd',
        '3d_invitational2021_team_create.csd',
        '3d_invitational2021_team_details.csd',
        '3d_mod_linbingliezhen_battle.csd',
        '3d_mod_linbingliezhen_choose.csd',
        '3d_mod_main.csd',
        '3d_mod_room.csd',
        '3d_sys_pop_full.csd',
        '3d_sys_pop_l.csd',
        '3d_sys_pop_m.csd',
        '3d_sys_pop_s.csd',
    ],
}


let csdFiles = [];
let result = {};

for(const key in list){
    list[key].forEach(element => {
        if(csdFiles.includes(element))
        {}else{
            csdFiles.push(element)
        }
    });
}
csdFiles.sort()
// console.log(csdFiles);
const picBelong = function(value){
    return Object.keys(list).filter(key => list[key].indexOf(value)>=0);
}
csdFiles.forEach(element => {
    const picList = picBelong(element);
    // console.log(picList);
    result[element] = picList;
})
console.log(result);